FROM python:3.12-slim

# pdf2image dependency
RUN apt-get update \
    && apt-get install -y poppler-utils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

RUN pip3 install poetry

WORKDIR  /backend

COPY /pyproject.toml .
COPY /README.md .

RUN poetry config virtualenvs.create false  \
    && poetry install --no-root

COPY server.py .

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "2"]